
import { test, expect } from '@playwright/test';
import { promises as fs } from 'fs';
import path from 'path';

test.describe('Feature CRUD', () => {
    test.beforeEach(async ({ page }) => {
        // Enable diagnostics
        page.on('console', msg => console.log(`PAGE LOG: ${msg.text()}`));
        page.on('pageerror', err => console.log(`PAGE ERROR: ${err.message}`));

        await page.addInitScript(() => {
            window.addEventListener('beforeunload', () => {
                window.collectCoverage && window.collectCoverage();
            });
        });

        await page.goto('/');

        const loginOverlay = page.locator('text=MML Map — Sign in');
        await expect(loginOverlay).toBeVisible({ timeout: 10000 });
        await page.fill('input[placeholder="Username"]', 'admin');
        await page.fill('input[placeholder="Password"]', 'admin');
        await page.click('button:has-text("Sign in")');
        await expect(loginOverlay).toBeHidden();

        // Wait for bootstrap (controls)
        await expect(page.locator('.ol-zoom-in')).toBeVisible({ timeout: 10000 });
    });

    test.afterEach(async ({ page }) => {
        const coverage = await page.evaluate(() => window.__coverage__);
        if (coverage) {
            await fs.writeFile(
                path.join('.nyc_output', `coverage-crud-${Date.now()}.json`),
                JSON.stringify(coverage)
            );
        }
    });

    test('should create and save a marker', async ({ page }) => {
        await page.click('#draw-menu-toggle');
        await expect(page.locator('#draw-dropdown')).toBeVisible();

        await page.click('#draw-marker-btn');
        // Dropdown closes automatically via closeAllDropdowns()
        await expect(page.locator('#draw-dropdown')).toBeHidden();
        // Small wait to ensure listener is attached
        await page.waitForTimeout(500);

        // Click on map canvas directly
        await page.locator('#map canvas').click({ position: { x: 400, y: 300 } });

        const form = page.locator('text=Add Marker');
        await expect(form).toBeVisible();

        // Use unique title with timestamp for test identification
        const testMarkerTitle = `Test Marker ${Date.now()}`;
        await page.fill('input[placeholder="Title (optional)"]', testMarkerTitle);
        await page.fill('textarea[placeholder="Description (optional)"]', 'Generated by E2E Test');

        // Specific selector
        await page.click('button.save-feature-btn');
        await expect(form).toBeHidden();
    });

    test('should create and save a polygon', async ({ page }) => {
        await page.click('#draw-menu-toggle');
        await expect(page.locator('#draw-dropdown')).toBeVisible();
        await page.click('#draw-polygon-btn');
        // Dropdown closes automatically via closeAllDropdowns()
        await expect(page.locator('#draw-dropdown')).toBeHidden();
        await page.waitForTimeout(500);

        const canvas = page.locator('#map canvas');
        await canvas.click({ position: { x: 150, y: 150 } });
        await canvas.click({ position: { x: 250, y: 150 } });
        await canvas.click({ position: { x: 250, y: 250 } });
        await canvas.dblclick({ position: { x: 150, y: 250 } });

        const form = page.locator('text=Add Polygon');
        await expect(form).toBeVisible();

        // Use unique title with timestamp for test identification
        const testPolygonTitle = `Test Polygon ${Date.now()}`;
        await page.fill('input[placeholder="Title (optional)"]', testPolygonTitle);
        await page.click('button.save-feature-btn');

        await expect(form).toBeHidden();
    });

    test('should delete a marker', async ({ page }) => {
        await page.click('#draw-menu-toggle');
        await expect(page.locator('#draw-dropdown')).toBeVisible();
        await page.click('#draw-marker-btn');
        // Dropdown closes automatically via closeAllDropdowns()
        await expect(page.locator('#draw-dropdown')).toBeHidden();
        await page.waitForTimeout(500);

        await page.locator('#map canvas').click({ position: { x: 500, y: 300 } });

        const form = page.locator('text=Add Marker');
        await expect(form).toBeVisible();
        await page.fill('input[placeholder="Title (optional)"]', 'To Delete');
        await page.click('button.save-feature-btn');
        await expect(form).toBeHidden();

        await page.waitForTimeout(1000);
        // Click the feature - need to make sure we click exactly where it is.
        // The viewport should be stable.
        await page.locator('#map canvas').click({ position: { x: 500, y: 300 } });

        // Form should appear
        await expect(form).toBeVisible();
        await page.click('button:has-text("Delete")');
        await expect(form).toBeHidden();
    });
});
